### ISSUE TITLE
create new window withing container (parentElement)

### ISSUE THREAD

**Issue by infantilo** [riversun/JSFrame.js#13]
Hi,
ist there a way to create windows within an container div and keep it withing this div's boundaries?
Tried to set the parentElement: IDOFCONTAINERDIVHERE without luck.
This would be needed to have nested windows.

after initializing jsFrame with an parentElement , the jsFrame.windowmanager.parentFrame is document,body , and therefore the windowmanagerdiv is created there.

Thanks for help

**Comment by riversun** [comment]
Is this what you want to do?

https://riversun.github.io/JSFrame.js/public/examples/v160/live-inside-element/index.html

Specify the parent element in JSFrame's initialization parameter.
The next step is to specify the parent element's style as "overflow:hidden" to prevent the window from overflowing from that elements.

**Comment by riversun** [comment]
Resolve with the correspondence of #50
Below is an example code to nested frames (window-in-window)

https://riversun.github.io/JSFrame.js/public/examples/v160/window-in-window/index.html
