### ISSUE TITLE
Add move and resize events 

### ISSUE THREAD

**Issue by riversun** [riversun/JSFrame.js#15]

**Comment by mobilebiz** [comment]
Hi, riversun.
Please tell me how can I use Move and Resize events?
My code is below, but this doesn't work.
I use jsframe.min.js version 1.6.0.
```
    const jsFrameShare = new JSFrame();
    // Create window
    const windowWidth = 800;
    const windowHeight = 600;
    frameShare = jsFrameShare.create({
      title: 'ScreenShare',
      left: 100,
      top: 100,
      width: windowWidth,
      height: windowHeight,
      style: {
        backgroundColor: 'rgba(255,255,255,0.9)',
        overflow: 'scroll',
      },
      appearanceName: 'yosemite',
      movable: true,  //Enable to be moved by mouse
      resizable: true,  //Enable to be resized by mouse
      html: '<div id="share_element"></div>',
    });

    // Button hide.
    frameShare.hideFrameComponent('closeButton');
    frameShare.hideFrameComponent('minimizeButton');
    frameShare.hideFrameComponent('zoomButton');

    // Move event.
    frameShare.on('move', (_flame) => {
      console.log(`Frame moved. ${_flame}`);
    });
    
    // Resize event.
    frameShare.on('resize', (_flame) => {
      console.log(`Frame resized. ${_flame}`);
    });
    
```

**Comment by riversun** [comment]
Hi,

Try changing your `frameShare.on('move', (_flame) `  to a  `frameShare.on('frame','move', (_flame)`

The frame#on method takes the following three arguments 

on(id, eventType, callbackFunc)

The id is often used as a selector to search within the content like "#button1", 
but the the only special behavior is when the id is set to "frame" or "window".

This means that you can receive the events of the frame itself.

Currently, 
the following values can be specified.

 "move"... When a window is moved, it fires.
 "resize"... Fires when the window is resized.
 "focus"... "focus" means got focus. It fires when the window is in focus.
 "blur"... "blur" means lost focus.It fires when the window loses focus.

thanks.

**Comment by mobilebiz** [comment]
Great! It worked!
Thank you for your quick response.
