### ISSUE TITLE
Window is hidden behind other elements

### ISSUE THREAD

**Issue by dominickciccone** [riversun/JSFrame.js#7]
The JSFrame window appears to be getting hidden behind some other elements on my page. These are elements I've have had to force to the front to work correctly with other aspects of my application. Any suggestions on forcing this to the font?
![window issue](https://user-images.githubusercontent.com/8568961/71730768-087db800-2e11-11ea-8aaf-fe84eb0dae51.JPG)
?

**Comment by docravendark** [comment]
Hi,

two suggestions: 

1. set z-index on window div higher than z-index from details bar
2. create the window (handler) as the last dom element if you dont use z-index (or dont want to)

hope this helps

**Comment by riversun** [comment]
By setting the parent element of jsFrame above the UI element you want to display below the jsFrame window, you will be able to display the jsFrame window at the top level.

```
this.jsFrame = new JSFrame({
    parentElement:document.body,//Set the parent element to which the jsFrame is attached here
});


```

**Comment by riversun** [comment]
For the release of V1.6, a new code example for the order of windows and other elements has been added to I've added it, so take a look at it.

https://riversun.github.io/JSFrame.js/public/examples/v160/window-order/index.html
